# Generated by Django 6.0.2 on 2026-02-17 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
