# Generated by Django 6.0.2 on 2026-02-26 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_seed_leases_tab'),
        ('legal', '0002_evidence_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalmatter',
            name='related_aircraft',
            field=models.ManyToManyField(blank=True, related_name='legal_matters', to='assets.aircraft'),
        ),
        migrations.AddField(
            model_name='legalmatter',
            name='related_investments',
            field=models.ManyToManyField(blank=True, related_name='legal_matters', to='assets.investment'),
        ),
        migrations.AddField(
            model_name='legalmatter',
            name='related_leases',
            field=models.ManyToManyField(blank=True, related_name='legal_matters', to='assets.lease'),
        ),
        migrations.AddField(
            model_name='legalmatter',
            name='related_loans',
            field=models.ManyToManyField(blank=True, related_name='legal_matters', to='assets.loan'),
        ),
        migrations.AddField(
            model_name='legalmatter',
            name='related_policies',
            field=models.ManyToManyField(blank=True, related_name='legal_matters', to='assets.insurancepolicy'),
        ),
        migrations.AddField(
            model_name='legalmatter',
            name='related_vehicles',
            field=models.ManyToManyField(blank=True, related_name='legal_matters', to='assets.vehicle'),
        ),
    ]
