# Generated by Django 6.0.2 on 2026-02-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0002_legalmatter_judgment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalmatter',
            name='matter_type',
            field=models.CharField(default='other', max_length=30),
        ),
    ]
