# Generated by Django 6.0.2 on 2026-03-03 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0003_seed_choices'),
        ('legal', '0003_legalmatter_related_aircraft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalmatter',
            name='related_conditions',
            field=models.ManyToManyField(blank=True, related_name='legal_matters', to='healthcare.condition'),
        ),
        migrations.AddField(
            model_name='legalmatter',
            name='related_prescriptions',
            field=models.ManyToManyField(blank=True, related_name='legal_matters', to='healthcare.prescription'),
        ),
        migrations.AddField(
            model_name='legalmatter',
            name='related_providers',
            field=models.ManyToManyField(blank=True, related_name='legal_matters', to='healthcare.provider'),
        ),
    ]
