# Generated by Django 6.0.2 on 2026-03-06 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0004_legalmatter_healthcare_m2m'),
        ('stakeholders', '0003_stakeholdertab'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('direction', models.CharField(choices=[('outbound', 'Outbound'), ('inbound', 'Inbound')], default='outbound', max_length=10)),
                ('method', models.CharField(max_length=30)),
                ('summary', models.TextField()),
                ('follow_up_needed', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('legal_matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='legal.legalmatter')),
                ('stakeholder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_communications', to='stakeholders.stakeholder')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
