# Generated by Django 6.0.2 on 2026-03-07 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0005_legalcommunication'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalcommunication',
            name='file',
            field=models.FileField(blank=True, upload_to='communications/'),
        ),
    ]
