# Generated by Django 6.0.2 on 2026-03-07 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0006_legalcommunication_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalcommunication',
            name='follow_up_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='legalcommunication',
            name='follow_up_completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legalcommunication',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
