# Generated by Django 6.0.2 on 2026-03-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0007_legalcommunication_subject_followup_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='gdrive_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='legalcommunication',
            name='gdrive_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
