# Generated by Django 6.0.2 on 2026-03-11 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0009_alter_evidence_gdrive_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('legal_matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='legal.legalmatter')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
