# Generated by Django 6.0.2 on 2026-03-11 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0010_add_legal_checklist_item'),
        ('stakeholders', '0005_stakeholder_firm_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('legal_matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_logs', to='legal.legalmatter')),
                ('stakeholder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_logs', to='stakeholders.stakeholder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
