# Generated by Django 6.0.2 on 2026-03-13 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0011_add_case_log'),
        ('stakeholders', '0005_stakeholder_firm_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('contacted', 'Contacted'), ('in_review', 'In Review'), ('interested', 'Interested'), ('declined', 'Declined'), ('engaged', 'Engaged'), ('on_hold', 'On Hold')], default='contacted', max_length=20)),
                ('scope', models.TextField(blank=True)),
                ('initial_contact_date', models.DateField()),
                ('response_date', models.DateField(blank=True, null=True)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('firm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_engagements', to='stakeholders.stakeholder')),
                ('legal_matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firm_engagements', to='legal.legalmatter')),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='legal.firmengagement')),
            ],
            options={
                'ordering': ['-initial_contact_date'],
                'unique_together': {('legal_matter', 'firm')},
            },
        ),
    ]
