# Generated by Django 6.0.2 on 2026-02-10 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stakeholders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('investment_type', models.CharField(blank=True, max_length=100)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notes_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('borrower_description', models.CharField(blank=True, max_length=255)),
                ('original_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('current_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('monthly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('next_payment_date', models.DateField(blank=True, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('collateral', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paid_off', 'Paid Off'), ('defaulted', 'Defaulted'), ('in_dispute', 'In Dispute')], default='active', max_length=20)),
                ('notes_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('jurisdiction', models.CharField(blank=True, max_length=255)),
                ('property_type', models.CharField(blank=True, max_length=100)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('owned', 'Owned'), ('under_contract', 'Under Contract'), ('sold', 'Sold'), ('in_dispute', 'In Dispute')], default='owned', max_length=20)),
                ('notes_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Real estate',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Ownership percentage (e.g., 50.00 for 50%)', max_digits=5, null=True)),
                ('role', models.CharField(blank=True, help_text='e.g., Investor, Co-investor, Fund Manager', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='assets.investment')),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_participations', to='stakeholders.stakeholder')),
            ],
            options={
                'verbose_name_plural': 'Investment participants',
                'ordering': ['-ownership_percentage', 'stakeholder__name'],
            },
        ),
        migrations.AddField(
            model_name='investment',
            name='stakeholders',
            field=models.ManyToManyField(blank=True, related_name='investments', through='assets.InvestmentParticipant', to='stakeholders.stakeholder'),
        ),
        migrations.CreateModel(
            name='LoanParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Ownership/liability percentage (e.g., 50.00 for 50%)', max_digits=5, null=True)),
                ('role', models.CharField(blank=True, help_text='e.g., Lender, Borrower, Co-borrower, Guarantor', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='assets.loan')),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_parties', to='stakeholders.stakeholder')),
            ],
            options={
                'verbose_name_plural': 'Loan parties',
                'ordering': ['role', '-ownership_percentage', 'stakeholder__name'],
            },
        ),
        migrations.AddField(
            model_name='loan',
            name='stakeholders',
            field=models.ManyToManyField(blank=True, related_name='loans', through='assets.LoanParty', to='stakeholders.stakeholder'),
        ),
        migrations.CreateModel(
            name='PropertyOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Ownership percentage (e.g., 50.00 for 50%)', max_digits=5, null=True)),
                ('role', models.CharField(blank=True, help_text='e.g., Owner, Co-owner, Partner', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='assets.realestate')),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_ownerships', to='stakeholders.stakeholder')),
            ],
            options={
                'verbose_name_plural': 'Property ownerships',
                'ordering': ['-ownership_percentage', 'stakeholder__name'],
            },
        ),
        migrations.AddField(
            model_name='realestate',
            name='stakeholders',
            field=models.ManyToManyField(blank=True, related_name='properties', through='assets.PropertyOwnership', to='stakeholders.stakeholder'),
        ),
    ]
