# Generated by Django 6.0.2 on 2026-02-09 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('stakeholders', '0002_alter_contactlog_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='stakeholder',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='lender',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='stakeholder',
        ),
        migrations.CreateModel(
            name='InvestmentParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Ownership percentage (e.g., 50.00 for 50%)', max_digits=5, null=True)),
                ('role', models.CharField(blank=True, help_text='e.g., Investor, Co-investor, Fund Manager', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='assets.investment')),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_participations', to='stakeholders.stakeholder')),
            ],
            options={
                'verbose_name_plural': 'Investment participants',
                'ordering': ['-ownership_percentage', 'stakeholder__name'],
            },
        ),
        migrations.AddField(
            model_name='investment',
            name='stakeholders',
            field=models.ManyToManyField(blank=True, related_name='investments', through='assets.InvestmentParticipant', to='stakeholders.stakeholder'),
        ),
        migrations.CreateModel(
            name='LoanParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Ownership/liability percentage (e.g., 50.00 for 50%)', max_digits=5, null=True)),
                ('role', models.CharField(blank=True, help_text='e.g., Lender, Borrower, Co-borrower, Guarantor', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='assets.loan')),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_parties', to='stakeholders.stakeholder')),
            ],
            options={
                'verbose_name_plural': 'Loan parties',
                'ordering': ['role', '-ownership_percentage', 'stakeholder__name'],
            },
        ),
        migrations.AddField(
            model_name='loan',
            name='stakeholders',
            field=models.ManyToManyField(blank=True, related_name='loans', through='assets.LoanParty', to='stakeholders.stakeholder'),
        ),
        migrations.CreateModel(
            name='PropertyOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Ownership percentage (e.g., 50.00 for 50%)', max_digits=5, null=True)),
                ('role', models.CharField(blank=True, help_text='e.g., Owner, Co-owner, Partner', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='assets.realestate')),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_ownerships', to='stakeholders.stakeholder')),
            ],
            options={
                'verbose_name_plural': 'Property ownerships',
                'ordering': ['-ownership_percentage', 'stakeholder__name'],
            },
        ),
        migrations.AddField(
            model_name='realestate',
            name='stakeholders',
            field=models.ManyToManyField(blank=True, related_name='properties', through='assets.PropertyOwnership', to='stakeholders.stakeholder'),
        ),
    ]
