# Generated by Django 6.0.2 on 2026-02-10 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='related_investment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='assets.investment', verbose_name='Investment'),
        ),
        migrations.AddField(
            model_name='loan',
            name='related_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='assets.realestate', verbose_name='Property'),
        ),
    ]
