# Generated by Django 6.0.2 on 2026-02-12 05:15

from django.db import migrations, models


def seed_asset_tabs(apps, schema_editor):
    AssetTab = apps.get_model("assets", "AssetTab")
    tabs = [
        {"key": "all", "label": "All", "asset_types": ["properties", "investments", "loans"], "sort_order": 0, "is_builtin": True},
        {"key": "properties", "label": "Properties", "asset_types": ["properties"], "sort_order": 1, "is_builtin": False},
        {"key": "investments", "label": "Investments", "asset_types": ["investments"], "sort_order": 2, "is_builtin": False},
        {"key": "loans", "label": "Loans", "asset_types": ["loans"], "sort_order": 3, "is_builtin": False},
    ]
    for tab in tabs:
        AssetTab.objects.create(**tab)


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_loan_related_asset_fks'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=100)),
                ('asset_types', models.JSONField(blank=True, default=list, help_text='List of asset type values for this tab')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_builtin', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.RunPython(seed_asset_tabs, migrations.RunPython.noop),
    ]
