# Generated by Django 6.0.2 on 2026-02-12 21:18

import django.db.models.deletion
from django.db import migrations, models


def seed_policy_types(apps, schema_editor):
    ChoiceOption = apps.get_model("dashboard", "ChoiceOption")
    policy_types = [
        ("policy_type", "auto", "Auto", 0),
        ("policy_type", "homeowners", "Homeowners", 1),
        ("policy_type", "commercial_property", "Commercial Property", 2),
        ("policy_type", "aviation", "Aviation", 3),
        ("policy_type", "umbrella", "Umbrella", 4),
        ("policy_type", "liability", "Liability", 5),
        ("policy_type", "life", "Life", 6),
        ("policy_type", "general", "General", 7),
    ]
    for category, value, label, sort_order in policy_types:
        ChoiceOption.objects.get_or_create(
            category=category, value=value,
            defaults={"label": label, "sort_order": sort_order},
        )


def update_all_asset_tab(apps, schema_editor):
    AssetTab = apps.get_model("assets", "AssetTab")
    try:
        all_tab = AssetTab.objects.get(key="all", is_builtin=True)
        if "policies" not in all_tab.asset_types:
            all_tab.asset_types = all_tab.asset_types + ["policies"]
            all_tab.save()
    except AssetTab.DoesNotExist:
        pass


def seed_insurance_tab(apps, schema_editor):
    AssetTab = apps.get_model("assets", "AssetTab")
    last = AssetTab.objects.order_by("-sort_order").first()
    next_order = (last.sort_order + 1) if last else 0
    AssetTab.objects.get_or_create(
        key="insurance",
        defaults={
            "label": "Insurance",
            "asset_types": ["policies"],
            "sort_order": next_order,
            "is_builtin": False,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_assettab'),
        ('dashboard', '0004_alter_choiceoption_category'),
        ('stakeholders', '0003_stakeholdertab'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('policy_number', models.CharField(blank=True, max_length=100)),
                ('policy_type', models.CharField(default='general', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='active', max_length=20)),
                ('premium_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('premium_frequency', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-Annual'), ('annual', 'Annual')], default='annual', max_length=20)),
                ('deductible', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('coverage_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('notes_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies_as_agent', to='stakeholders.stakeholder', verbose_name='Agent')),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies_as_carrier', to='stakeholders.stakeholder', verbose_name='Carrier')),
                ('covered_properties', models.ManyToManyField(blank=True, related_name='insurance_policies', to='assets.realestate')),
            ],
            options={
                'verbose_name_plural': 'Insurance policies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PolicyHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, help_text='e.g., Named Insured, Beneficiary, Additional Insured', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policyholders', to='assets.insurancepolicy')),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policyholder_roles', to='stakeholders.stakeholder')),
            ],
            options={
                'verbose_name_plural': 'Policy holders',
                'ordering': ['role', 'stakeholder__name'],
            },
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='stakeholders',
            field=models.ManyToManyField(blank=True, related_name='insurance_policies', through='assets.PolicyHolder', to='stakeholders.stakeholder'),
        ),
        migrations.RunPython(seed_policy_types, migrations.RunPython.noop),
        migrations.RunPython(update_all_asset_tab, migrations.RunPython.noop),
        migrations.RunPython(seed_insurance_tab, migrations.RunPython.noop),
    ]
