# Generated by Django 6.0.2 on 2026-02-12 22:25

import django.db.models.deletion
from django.db import migrations, models


def seed_choice_options_and_tabs(apps, schema_editor):
    ChoiceOption = apps.get_model("dashboard", "ChoiceOption")
    AssetTab = apps.get_model("assets", "AssetTab")

    # Seed vehicle_type choices
    vehicle_types = [
        ("vehicle_type", "sedan", "Sedan", 0),
        ("vehicle_type", "suv", "SUV", 1),
        ("vehicle_type", "truck", "Truck", 2),
        ("vehicle_type", "motorcycle", "Motorcycle", 3),
        ("vehicle_type", "rv", "RV", 4),
        ("vehicle_type", "van", "Van", 5),
        ("vehicle_type", "boat", "Boat", 6),
        ("vehicle_type", "other", "Other", 7),
    ]
    for cat, val, label, order in vehicle_types:
        ChoiceOption.objects.get_or_create(
            category=cat, value=val,
            defaults={"label": label, "sort_order": order},
        )

    # Seed aircraft_type choices
    aircraft_types = [
        ("aircraft_type", "single_engine", "Single Engine", 0),
        ("aircraft_type", "multi_engine", "Multi Engine", 1),
        ("aircraft_type", "turboprop", "Turboprop", 2),
        ("aircraft_type", "jet", "Jet", 3),
        ("aircraft_type", "helicopter", "Helicopter", 4),
        ("aircraft_type", "glider", "Glider", 5),
    ]
    for cat, val, label, order in aircraft_types:
        ChoiceOption.objects.get_or_create(
            category=cat, value=val,
            defaults={"label": label, "sort_order": order},
        )

    # Update "All" builtin tab to include new types
    try:
        all_tab = AssetTab.objects.get(key="all")
        for t in ("vehicles", "aircraft"):
            if t not in all_tab.asset_types:
                all_tab.asset_types.append(t)
        all_tab.save()
    except AssetTab.DoesNotExist:
        pass

    # Seed new tabs
    last = AssetTab.objects.order_by("-sort_order").first()
    next_order = (last.sort_order + 1) if last else 5
    AssetTab.objects.get_or_create(
        key="vehicles",
        defaults={"label": "Vehicles", "asset_types": ["vehicles"], "sort_order": next_order, "is_builtin": False},
    )
    AssetTab.objects.get_or_create(
        key="aircraft",
        defaults={"label": "Aircraft", "asset_types": ["aircraft"], "sort_order": next_order + 1, "is_builtin": False},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_insurancepolicy_policyholder_and_more'),
        ('dashboard', '0005_alter_choiceoption_category'),
        ('stakeholders', '0003_stakeholdertab'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tail_number', models.CharField(blank=True, max_length=20, verbose_name='Tail Number')),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('make', models.CharField(blank=True, max_length=100)),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='Model')),
                ('aircraft_type', models.CharField(default='single_engine', max_length=30)),
                ('num_engines', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('base_airport', models.CharField(blank=True, max_length=10, verbose_name='Base Airport')),
                ('total_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Total Hours')),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('in_maintenance', 'In Maintenance'), ('stored', 'Stored'), ('sold', 'Sold'), ('in_dispute', 'In Dispute')], default='active', max_length=20)),
                ('registration_country', models.CharField(blank=True, default='US', max_length=50)),
                ('notes_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Aircraft',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('vin', models.CharField(blank=True, max_length=50, verbose_name='VIN')),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('make', models.CharField(blank=True, max_length=100)),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='Model')),
                ('vehicle_type', models.CharField(default='other', max_length=30)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('license_plate', models.CharField(blank=True, max_length=20)),
                ('registration_state', models.CharField(blank=True, max_length=50)),
                ('mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('stored', 'Stored'), ('sold', 'Sold'), ('in_dispute', 'In Dispute')], default='active', max_length=20)),
                ('notes_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='covered_aircraft',
            field=models.ManyToManyField(blank=True, related_name='insurance_policies', to='assets.aircraft'),
        ),
        migrations.CreateModel(
            name='AircraftOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Ownership percentage (e.g., 50.00 for 50%)', max_digits=5, null=True)),
                ('role', models.CharField(blank=True, help_text='e.g., Owner, Co-owner, Operator', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='assets.aircraft')),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircraft_ownerships', to='stakeholders.stakeholder')),
            ],
            options={
                'verbose_name_plural': 'Aircraft owners',
                'ordering': ['-ownership_percentage', 'stakeholder__name'],
            },
        ),
        migrations.AddField(
            model_name='aircraft',
            name='stakeholders',
            field=models.ManyToManyField(blank=True, related_name='aircraft_owned', through='assets.AircraftOwner', to='stakeholders.stakeholder'),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='covered_vehicles',
            field=models.ManyToManyField(blank=True, related_name='insurance_policies', to='assets.vehicle'),
        ),
        migrations.CreateModel(
            name='VehicleOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Ownership percentage (e.g., 50.00 for 50%)', max_digits=5, null=True)),
                ('role', models.CharField(blank=True, help_text='e.g., Owner, Co-owner', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_ownerships', to='stakeholders.stakeholder')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='assets.vehicle')),
            ],
            options={
                'verbose_name_plural': 'Vehicle owners',
                'ordering': ['-ownership_percentage', 'stakeholder__name'],
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='stakeholders',
            field=models.ManyToManyField(blank=True, related_name='vehicles', through='assets.VehicleOwner', to='stakeholders.stakeholder'),
        ),
        migrations.RunPython(seed_choice_options_and_tabs, migrations.RunPython.noop),
    ]
