# Generated by Django 6.0.2 on 2026-02-13 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_aircraft_vehicle_insurancepolicy_covered_aircraft_and_more'),
        ('stakeholders', '0003_stakeholdertab'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aircraftowner',
            unique_together={('aircraft', 'stakeholder')},
        ),
        migrations.AlterUniqueTogether(
            name='investmentparticipant',
            unique_together={('investment', 'stakeholder')},
        ),
        migrations.AlterUniqueTogether(
            name='loanparty',
            unique_together={('loan', 'stakeholder')},
        ),
        migrations.AlterUniqueTogether(
            name='policyholder',
            unique_together={('policy', 'stakeholder')},
        ),
        migrations.AlterUniqueTogether(
            name='propertyownership',
            unique_together={('property', 'stakeholder')},
        ),
        migrations.AlterUniqueTogether(
            name='vehicleowner',
            unique_together={('vehicle', 'stakeholder')},
        ),
    ]
