# Generated by Django 6.0.2 on 2026-02-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_unique_together_through_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='default_interest_rate',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Rate applied when loan is in default', max_digits=6, null=True, verbose_name='Default interest rate (%)'),
        ),
        migrations.AddField(
            model_name='loan',
            name='is_hard_money',
            field=models.BooleanField(default=False, verbose_name='Hard money loan'),
        ),
    ]
