# Generated by Django 6.0.2 on 2026-02-16 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_loan_hard_money_default_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='related_aircraft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='assets.aircraft', verbose_name='Aircraft'),
        ),
        migrations.AddField(
            model_name='loan',
            name='related_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='assets.vehicle', verbose_name='Vehicle'),
        ),
    ]
