# Generated by Django 6.0.2 on 2026-02-24 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_loan_related_vehicle_aircraft'),
        ('stakeholders', '0003_stakeholdertab'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lease_type', models.CharField(default='residential', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('upcoming', 'Upcoming'), ('terminated', 'Terminated'), ('month_to_month', 'Month-to-Month')], default='active', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, db_index=True, null=True)),
                ('monthly_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('security_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rent_due_day', models.PositiveSmallIntegerField(blank=True, help_text='Day of month rent is due (1-31)', null=True)),
                ('renewal_type', models.CharField(choices=[('none', 'None'), ('auto', 'Auto-Renew'), ('option', 'Option to Renew'), ('negotiable', 'Negotiable')], default='none', max_length=20)),
                ('renewal_terms', models.TextField(blank=True)),
                ('escalation_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Annual escalation %')),
                ('notes_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='assets.realestate', verbose_name='Property')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeaseParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, help_text='e.g., Tenant, Landlord, Guarantor, Property Manager', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='assets.lease')),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_parties', to='stakeholders.stakeholder')),
            ],
            options={
                'verbose_name_plural': 'Lease parties',
                'ordering': ['role', 'stakeholder__name'],
                'unique_together': {('lease', 'stakeholder')},
            },
        ),
        migrations.AddField(
            model_name='lease',
            name='stakeholders',
            field=models.ManyToManyField(blank=True, related_name='leases', through='assets.LeaseParty', to='stakeholders.stakeholder'),
        ),
    ]
