# Generated by Django 6.0.2 on 2026-03-04 19:37

from django.db import migrations, models


def populate_tenant_from_name(apps, schema_editor):
    """Auto-populate tenant field from existing property names.

    Properties named like "7-Eleven - 509 Bates Ave" get tenant="7-Eleven".
    """
    RealEstate = apps.get_model("assets", "RealEstate")
    for prop in RealEstate.objects.all():
        if " - " in prop.name:
            tenant = prop.name.split(" - ", 1)[0].strip()
            if tenant:
                prop.tenant = tenant
                prop.save(update_fields=["tenant"])


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_seed_leases_tab'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='tenant',
            field=models.CharField(blank=True, help_text='Brand or tenant name (e.g. 7-Eleven, CVS)', max_length=255),
        ),
        migrations.RunPython(populate_tenant_from_name, migrations.RunPython.noop),
    ]
