# Generated by Django 6.0.2 on 2026-03-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_add_tenant_to_realestate'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='deferred_gain',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Deferred gain / future tax liability', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='realestate',
            name='equity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='314SG equity position', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='realestate',
            name='income_source',
            field=models.CharField(blank=True, help_text='Distribution type (e.g. "D", "Above Pref", "Vacant")', max_length=100),
        ),
        migrations.AddField(
            model_name='realestate',
            name='loan_balance_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Outstanding loan balance at time of import', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='realestate',
            name='monthly_accrued_income',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly accrued (undistributed) income', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='realestate',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly income from property', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='realestate',
            name='sold_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='realestate',
            name='total_accrued_pref_return',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total accrued preferred return', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='realestate',
            name='total_unreturned_capital',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='All-investors unreturned capital', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='realestate',
            name='unreturned_capital',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='314SG unreturned capital', max_digits=14, null=True),
        ),
    ]
