# Generated by Django 6.0.2 on 2026-03-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_add_financial_fields_to_realestate'),
        ('stakeholders', '0003_stakeholdertab'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aircraftowner',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='investmentparticipant',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='propertyownership',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='vehicleowner',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='aircraftowner',
            name='role',
            field=models.CharField(blank=True, help_text='e.g., Owner, Co-owner, Operator, Pilot, Mechanic', max_length=100),
        ),
        migrations.AlterField(
            model_name='investmentparticipant',
            name='role',
            field=models.CharField(blank=True, help_text='e.g., Investor, Co-investor, Fund Manager, Advisor, Broker, Consultant', max_length=100),
        ),
        migrations.AlterField(
            model_name='propertyownership',
            name='role',
            field=models.CharField(blank=True, help_text='e.g., Owner, Co-owner, Partner, Contractor, Builder, Developer, Agent, Manager', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicleowner',
            name='role',
            field=models.CharField(blank=True, help_text='e.g., Owner, Co-owner, Driver, Mechanic, Dealer', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='aircraftowner',
            unique_together={('aircraft', 'stakeholder', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='investmentparticipant',
            unique_together={('investment', 'stakeholder', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='leaseparty',
            unique_together={('lease', 'stakeholder', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='loanparty',
            unique_together={('loan', 'stakeholder', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='policyholder',
            unique_together={('policy', 'stakeholder', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='propertyownership',
            unique_together={('property', 'stakeholder', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='vehicleowner',
            unique_together={('vehicle', 'stakeholder', 'role')},
        ),
    ]
