# Generated by Django 6.0.2 on 2026-02-10 04:40

from django.db import migrations, models

from dashboard.choice_seed_data import SEED_DATA


def seed_choices(apps, schema_editor):
    ChoiceOption = apps.get_model("dashboard", "ChoiceOption")
    for category, value, label, sort_order in SEED_DATA:
        ChoiceOption.objects.get_or_create(
            category=category,
            value=value,
            defaults={"label": label, "sort_order": sort_order},
        )


def unseed_choices(apps, schema_editor):
    ChoiceOption = apps.get_model("dashboard", "ChoiceOption")
    ChoiceOption.objects.all().delete()


def add_firm_entity_type(apps, schema_editor):
    ChoiceOption = apps.get_model("dashboard", "ChoiceOption")
    ChoiceOption.objects.get_or_create(
        category="entity_type",
        value="firm",
        defaults={"label": "Firm", "sort_order": 7},
    )


def remove_firm_entity_type(apps, schema_editor):
    ChoiceOption = apps.get_model("dashboard", "ChoiceOption")
    ChoiceOption.objects.filter(category="entity_type", value="firm").delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(blank=True, default='', max_length=255, verbose_name='SMTP host')),
                ('smtp_port', models.PositiveIntegerField(default=587, verbose_name='SMTP port')),
                ('use_tls', models.BooleanField(default=True, verbose_name='Use TLS')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='Use SSL')),
                ('username', models.CharField(blank=True, default='', max_length=255, verbose_name='Username')),
                ('password', models.CharField(blank=True, default='', max_length=255, verbose_name='Password')),
                ('from_email', models.EmailField(default='noreply@controlcenter.local', max_length=254, verbose_name='From email')),
                ('admin_email', models.EmailField(default='admin@controlcenter.local', max_length=254, verbose_name='Admin email (recipient)')),
                ('notifications_enabled', models.BooleanField(default=False, verbose_name='Enable email notifications')),
            ],
            options={
                'verbose_name': 'Email Settings',
                'verbose_name_plural': 'Email Settings',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChoiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('entity_type', 'Stakeholder Type'), ('contact_method', 'Contact Method'), ('matter_type', 'Legal Matter Type'), ('note_type', 'Note Type')], db_index=True, max_length=30)),
                ('value', models.CharField(max_length=30)),
                ('label', models.CharField(max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'sort_order', 'label'],
                'unique_together': {('category', 'value')},
            },
        ),
        migrations.RunPython(
            code=seed_choices,
            reverse_code=unseed_choices,
        ),
        migrations.RunPython(
            code=add_firm_entity_type,
            reverse_code=remove_firm_entity_type,
        ),
    ]
