# Generated by Django 6.0.2 on 2026-02-10 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleDataStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_loaded', models.BooleanField(default=False)),
                ('manifest', models.JSONField(blank=True, default=dict)),
                ('loaded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sample Data Status',
                'verbose_name_plural': 'Sample Data Status',
            },
        ),
    ]
