# Generated by Django 6.0.2 on 2026-02-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('entity_type', 'Stakeholder Type'), ('contact_method', 'Contact Method'), ('matter_type', 'Legal Matter Type'), ('note_type', 'Note Type')], db_index=True, max_length=30)),
                ('value', models.CharField(max_length=30)),
                ('label', models.CharField(max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'sort_order', 'label'],
                'unique_together': {('category', 'value')},
            },
        ),
    ]
