# Generated by Django 6.0.2 on 2026-02-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_backfill_sample_data_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choiceoption',
            name='category',
            field=models.CharField(choices=[('entity_type', 'Stakeholder Type'), ('contact_method', 'Contact Method'), ('matter_type', 'Legal Matter Type'), ('note_type', 'Note Type'), ('policy_type', 'Insurance Policy Type')], db_index=True, max_length=30),
        ),
    ]
