# Generated by Django 6.0.2 on 2026-02-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_choiceoption_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choiceoption',
            name='category',
            field=models.CharField(choices=[('entity_type', 'Stakeholder Type'), ('contact_method', 'Contact Method'), ('matter_type', 'Legal Matter Type'), ('note_type', 'Note Type'), ('policy_type', 'Insurance Policy Type'), ('vehicle_type', 'Vehicle Type'), ('aircraft_type', 'Aircraft Type')], db_index=True, max_length=30),
        ),
    ]
