# Generated by Django 6.0.2 on 2026-02-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_choiceoption_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enable automated backups')),
                ('frequency', models.CharField(choices=[('D', 'Daily'), ('H', 'Hourly'), ('W', 'Weekly')], default='D', max_length=1)),
                ('time_hour', models.PositiveSmallIntegerField(default=0, verbose_name='Hour (0-23)')),
                ('time_minute', models.PositiveSmallIntegerField(default=0, verbose_name='Minute (0-59)')),
                ('retention_count', models.PositiveSmallIntegerField(default=7, verbose_name='Backups to keep')),
            ],
            options={
                'verbose_name': 'Backup Settings',
                'verbose_name_plural': 'Backup Settings',
            },
        ),
    ]
