# Generated by Django 6.0.2 on 2026-02-15 21:07

from django.db import migrations


def update_email_defaults(apps, schema_editor):
    """Update email defaults from legacy.local to controlcenter.local."""
    EmailSettings = apps.get_model("dashboard", "EmailSettings")
    for obj in EmailSettings.objects.all():
        changed = False
        if obj.from_email == "noreply@legacy.local":
            obj.from_email = "noreply@controlcenter.local"
            changed = True
        if obj.admin_email == "admin@legacy.local":
            obj.admin_email = "admin@controlcenter.local"
            changed = True
        if changed:
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_backupsettings'),
    ]

    operations = [
        migrations.RunPython(update_email_defaults, migrations.RunPython.noop),
    ]
