# Generated by Django 6.0.2 on 2026-02-16 21:45

from django.db import migrations


CASHFLOW_CATEGORIES = [
    ("cashflow_category", "rental_income", "Rental Income", 0),
    ("cashflow_category", "mortgage", "Mortgage", 1),
    ("cashflow_category", "loan_payment", "Loan Payment", 2),
    ("cashflow_category", "insurance", "Insurance", 3),
    ("cashflow_category", "legal_fees", "Legal Fees", 4),
    ("cashflow_category", "renovation", "Renovation", 5),
    ("cashflow_category", "investment", "Investment", 6),
    ("cashflow_category", "investment_income", "Investment Income", 7),
    ("cashflow_category", "professional_services", "Professional Services", 8),
    ("cashflow_category", "acquisition", "Acquisition", 9),
    ("cashflow_category", "taxes", "Taxes", 10),
    ("cashflow_category", "maintenance", "Maintenance", 11),
    ("cashflow_category", "other", "Other", 12),
]


def seed(apps, schema_editor):
    ChoiceOption = apps.get_model("dashboard", "ChoiceOption")
    for category, value, label, sort_order in CASHFLOW_CATEGORIES:
        ChoiceOption.objects.get_or_create(
            category=category, value=value,
            defaults={"label": label, "sort_order": sort_order},
        )


def unseed(apps, schema_editor):
    ChoiceOption = apps.get_model("dashboard", "ChoiceOption")
    ChoiceOption.objects.filter(category="cashflow_category").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_add_cashflow_category_choice'),
    ]

    operations = [
        migrations.RunPython(seed, unseed),
    ]
