# Generated by Django 6.0.2 on 2026-03-03 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_choiceoption_category_healthcare'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarFeedSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='Enable calendar feed')),
                ('token', models.CharField(blank=True, default='', max_length=64, verbose_name='Feed token')),
            ],
            options={
                'verbose_name': 'Calendar Feed Settings',
                'verbose_name_plural': 'Calendar Feed Settings',
            },
        ),
    ]
