# Generated by Django 6.0.2 on 2026-03-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_add_calendar_feed_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarfeedsettings',
            name='event_types',
            field=models.JSONField(blank=True, default=dict, verbose_name='Enabled event types'),
        ),
    ]
