# Generated by Django 6.0.2 on 2026-03-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_add_event_types_to_calendar_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarfeedsettings',
            name='reminders',
            field=models.JSONField(blank=True, default=dict, verbose_name='Reminder settings'),
        ),
    ]
