# Generated by Django 6.0.2 on 2026-03-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_add_reminders_to_calendar_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choiceoption',
            name='category',
            field=models.CharField(choices=[('entity_type', 'Stakeholder Type'), ('firm_type', 'Firm Type'), ('contact_method', 'Contact Method'), ('matter_type', 'Legal Matter Type'), ('note_type', 'Note Type'), ('policy_type', 'Insurance Policy Type'), ('vehicle_type', 'Vehicle Type'), ('aircraft_type', 'Aircraft Type'), ('cashflow_category', 'Cash Flow Category'), ('lease_type', 'Lease Type'), ('provider_type', 'Provider Type'), ('test_type', 'Test Type')], db_index=True, max_length=30),
        ),
    ]
