# Generated by Django 6.0.2 on 2026-03-09 19:56

from django.db import migrations


DOCUMENT_CATEGORIES = [
    ("document_category", "deed", "Deed", 0),
    ("document_category", "lease", "Lease", 1),
    ("document_category", "appraisal", "Appraisal", 2),
    ("document_category", "tax_return", "Tax Return", 3),
    ("document_category", "insurance_cert", "Insurance Certificate", 4),
    ("document_category", "formation_doc", "Formation Document", 5),
    ("document_category", "operating_agreement", "Operating Agreement", 6),
    ("document_category", "operating_statement", "Operating Statement", 7),
    ("document_category", "investor_report", "Investor Report", 8),
    ("document_category", "k1", "K-1", 9),
    ("document_category", "closing_doc", "Closing Document", 10),
    ("document_category", "correspondence", "Correspondence", 11),
    ("document_category", "other", "Other", 12),
]


def seed_document_categories(apps, schema_editor):
    ChoiceOption = apps.get_model("dashboard", "ChoiceOption")
    for category, value, label, sort_order in DOCUMENT_CATEGORIES:
        ChoiceOption.objects.get_or_create(
            category=category, value=value,
            defaults={"label": label, "sort_order": sort_order},
        )


def remove_document_categories(apps, schema_editor):
    ChoiceOption = apps.get_model("dashboard", "ChoiceOption")
    ChoiceOption.objects.filter(category="document_category").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_seed_firm_type_choices'),
    ]

    operations = [
        migrations.RunPython(seed_document_categories, remove_document_categories),
    ]
