# Generated by Django 6.0.2 on 2026-02-16 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_loan_related_vehicle_aircraft'),
        ('cashflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflowentry',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cashflowentry',
            name='recurrence_rule',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20),
        ),
        migrations.AddField(
            model_name='cashflowentry',
            name='related_investment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_flow_entries', to='assets.investment'),
        ),
    ]
