# Generated by Django 6.0.2 on 2026-02-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_assettab'),
        ('notes', '0003_tag_folder_note_enhancements'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='related_investments',
            field=models.ManyToManyField(blank=True, related_name='notes', to='assets.investment'),
        ),
        migrations.AddField(
            model_name='note',
            name='related_loans',
            field=models.ManyToManyField(blank=True, related_name='notes', to='assets.loan'),
        ),
    ]
