# Generated by Django 6.0.2 on 2026-02-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_insurancepolicy_policyholder_and_more'),
        ('notes', '0004_add_related_investments_loans'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='related_policies',
            field=models.ManyToManyField(blank=True, related_name='notes', to='assets.insurancepolicy'),
        ),
    ]
