# Generated by Django 6.0.2 on 2026-02-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_aircraft_vehicle_insurancepolicy_covered_aircraft_and_more'),
        ('notes', '0005_note_related_policies'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='related_aircraft',
            field=models.ManyToManyField(blank=True, related_name='notes', to='assets.aircraft'),
        ),
        migrations.AddField(
            model_name='note',
            name='related_vehicles',
            field=models.ManyToManyField(blank=True, related_name='notes', to='assets.vehicle'),
        ),
    ]
