# Generated by Django 6.0.2 on 2026-02-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_lease_leaseparty_lease_stakeholders'),
        ('notes', '0006_note_related_aircraft_note_related_vehicles'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='related_leases',
            field=models.ManyToManyField(blank=True, related_name='notes', to='assets.lease'),
        ),
    ]
