# Generated by Django 6.0.2 on 2026-03-03 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0003_seed_choices'),
        ('notes', '0007_note_related_leases'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='related_appointments',
            field=models.ManyToManyField(blank=True, related_name='notes', to='healthcare.appointment'),
        ),
        migrations.AddField(
            model_name='note',
            name='related_conditions',
            field=models.ManyToManyField(blank=True, related_name='notes', to='healthcare.condition'),
        ),
        migrations.AddField(
            model_name='note',
            name='related_prescriptions',
            field=models.ManyToManyField(blank=True, related_name='notes', to='healthcare.prescription'),
        ),
        migrations.AddField(
            model_name='note',
            name='related_providers',
            field=models.ManyToManyField(blank=True, related_name='notes', to='healthcare.provider'),
        ),
        migrations.AddField(
            model_name='note',
            name='related_visits',
            field=models.ManyToManyField(blank=True, related_name='notes', to='healthcare.visit'),
        ),
    ]
