# Generated by Django 6.0.2 on 2026-03-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_seed_healthcare_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='gdrive_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, upload_to='attachments/'),
        ),
    ]
