# Generated by Django 6.0.2 on 2026-03-09 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_add_gdrive_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='gdrive_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Google Drive URL'),
        ),
    ]
