# Generated by Django 6.0.2 on 2026-03-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_alter_attachment_gdrive_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScratchPad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled', max_length=255)),
                ('content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processed', 'Processed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('meeting_date', models.DateField(blank=True, null=True)),
                ('participants_text', models.TextField(blank=True, help_text='Raw participant names before linking')),
                ('client_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
