# Generated by Django 6.0.2 on 2026-03-04 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0003_seed_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
