# Generated by Django 6.0.2 on 2026-03-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0004_appointment_address_appointment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='gdrive_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
