# Generated by Django 6.0.2 on 2026-03-09 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0013_allow_multiple_roles_per_stakeholder'),
        ('legal', '0007_legalcommunication_subject_followup_status'),
        ('stakeholders', '0005_stakeholder_firm_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDriveSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_connected', models.BooleanField(default=False)),
                ('client_id', models.CharField(blank=True, max_length=255)),
                ('client_secret', models.CharField(blank=True, max_length=255)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('refresh_token', models.TextField(blank=True)),
                ('access_token', models.TextField(blank=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('connected_email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Google Drive Settings',
                'verbose_name_plural': 'Google Drive Settings',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('gdrive_file_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Google Drive File ID')),
                ('gdrive_url', models.URLField(blank=True, max_length=500, verbose_name='Google Drive URL')),
                ('gdrive_mime_type', models.CharField(blank=True, max_length=100)),
                ('gdrive_file_name', models.CharField(blank=True, max_length=255, verbose_name='Original filename')),
                ('file', models.FileField(blank=True, upload_to='documents/')),
                ('notes_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_aircraft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='assets.aircraft')),
                ('related_investment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='assets.investment')),
                ('related_lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='assets.lease')),
                ('related_legal_matter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='legal.legalmatter')),
                ('related_loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='assets.loan')),
                ('related_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='assets.insurancepolicy')),
                ('related_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='assets.realestate')),
                ('related_stakeholder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='stakeholders.stakeholder')),
                ('related_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='assets.vehicle')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
