# Generated by Django 6.0.2 on 2026-03-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='googledrivesettings',
            name='project_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
