# Generated by Django 6.0.2 on 2026-03-11 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_add_project_number_to_gdrive_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='googledrivesettings',
            name='picker_debug',
            field=models.BooleanField(default=False),
        ),
    ]
