# Generated by Django 6.0.2

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_googledrivefolderbookmark'),
        ('tasks', '0014_add_tasklink_remove_reference_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='related_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='tasks.task'),
        ),
    ]
