# Generated by Django 6.0.2 on 2026-06-02 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_related_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googledrivefolderbookmark',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
