"""
Django settings for Control Center project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'true').lower() in ('true', '1', 'yes')

# SECURITY WARNING: keep the secret key used in production secret!
_secret_key_env = os.environ.get('SECRET_KEY')
if _secret_key_env:
    SECRET_KEY = _secret_key_env
elif DEBUG:
    SECRET_KEY = 'django-insecure-yltc=n0-m5px5i2xov#tz3n%yv6mhzh+f@-xb%n1)m&*1h79ah'
else:
    raise ValueError('SECRET_KEY environment variable is required when DEBUG=False')

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    # Third-party
    'django_q',
    # Project apps
    'stakeholders',
    'assets',
    'legal',
    'tasks',
    'cashflow',
    'notes',
    'healthcare',
    'documents',
    'email_links',
    'checklists',
    'dashboard',
    'assistant',
]

# Anthropic API
ANTHROPIC_API_KEY = os.environ.get('ANTHROPIC_API_KEY', '')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# SQLite concurrency: gunicorn gthread workers, the assistant's stream worker
# + toucher threads, and qcluster all write to one file. The stock 5s busy
# timeout produced intermittent "database is locked" under overlap, and
# DEFERRED transactions upgrade read→write mid-transaction, which is where
# SQLite deadlocks instead of waiting. IMMEDIATE takes the write lock at
# BEGIN, so transaction.atomic() blocks (bounded by the busy timeout) rather
# than erroring — and it serializes the assistant's check-then-mutate guards
# (views._live_running_turn + delete) against turn admission's INSERT.
# journal_mode=WAL is already persisted in the DB file; re-asserting it here
# is idempotent and covers fresh databases. The in-memory TEST database
# ignores WAL (returns 'memory') — harmless.
#
# init_command is the SINGLE source of truth for per-connection pragmas.
# These used to be set by a connection_created signal in dashboard/apps.py,
# which fired after init_command and silently overrode busy_timeout with a
# conflicting value — that handler is gone; add pragmas HERE, not in a
# signal. (foreign_keys=ON is set by Django's sqlite3 backend itself.)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': Path(os.environ.get('DATABASE_PATH', BASE_DIR / 'db.sqlite3')),
        'OPTIONS': {
            'timeout': 20,
            'transaction_mode': 'IMMEDIATE',
            'init_command': (
                'PRAGMA journal_mode=WAL; '
                'PRAGMA busy_timeout=20000; '
                'PRAGMA synchronous=NORMAL; '
                'PRAGMA cache_size=-20000;'
            ),
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Los_Angeles'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

if not DEBUG:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

    # Production security settings — gated behind ENABLE_SSL env var
    # Default off: this app runs behind VPN/ngrok which handles SSL termination
    _enable_ssl = os.environ.get('ENABLE_SSL', 'false').lower() in ('true', '1', 'yes')
    SECURE_SSL_REDIRECT = _enable_ssl
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_HSTS_SECONDS = 31536000 if _enable_ssl else 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = _enable_ssl
    SECURE_HSTS_PRELOAD = _enable_ssl
    SESSION_COOKIE_SECURE = _enable_ssl
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_SECURE = _enable_ssl
    CSRF_COOKIE_HTTPONLY = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django-Q2 task queue (ORM broker — no Redis needed)
Q_CLUSTER = {
    'name': 'ControlCenter',
    'workers': 2,
    'timeout': 60,
    'retry': 120,
    'queue_limit': 50,
    'orm': 'default',
}

# Email configuration
# NOTE: SMTP settings for notifications are now managed via the UI at /settings/email/
# (dashboard.models.EmailSettings). The settings below are kept as Django defaults.
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')

ADMIN_EMAIL = 'admin@controlcenter.local'
DEFAULT_FROM_EMAIL = 'noreply@controlcenter.local'

# Logging — route app-level loggers to Docker stdout.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {'class': 'logging.StreamHandler'},
    },
    'loggers': {
        'assistant': {'handlers': ['console'], 'level': 'INFO'},
    },
}
