from django.urls import path
from . import views

app_name = "assets"

urlpatterns = [
    # Unified asset list
    path("", views.asset_list, name="asset_list"),
    # Asset tab settings
    path("tabs/", views.asset_tab_settings, name="asset_tab_settings"),
    path("tabs/add/", views.asset_tab_add, name="asset_tab_add"),
    path("tabs/<int:pk>/edit/", views.asset_tab_edit, name="asset_tab_edit"),
    path("tabs/<int:pk>/delete/", views.asset_tab_delete, name="asset_tab_delete"),
    # Real Estate
    path("real-estate/", views.RealEstateListView.as_view(), name="realestate_list"),
    path("real-estate/<int:pk>/inline-status/", views.inline_update_realestate_status, name="realestate_inline_status"),
    path("real-estate/export/", views.export_realestate_csv, name="realestate_export_csv"),
    path("real-estate/create/", views.RealEstateCreateView.as_view(), name="realestate_create"),
    path("real-estate/<int:pk>/", views.RealEstateDetailView.as_view(), name="realestate_detail"),
    path("real-estate/<int:pk>/pdf/", views.export_pdf_realestate_detail, name="realestate_export_pdf"),
    path("real-estate/<int:pk>/edit/", views.RealEstateUpdateView.as_view(), name="realestate_edit"),
    path("real-estate/<int:pk>/delete/", views.RealEstateDeleteView.as_view(), name="realestate_delete"),
    path("real-estate/<int:pk>/policy/link/", views.property_policy_link, name="property_policy_link"),
    path("real-estate/<int:pk>/policy/<int:policy_pk>/unlink/", views.property_policy_unlink, name="property_policy_unlink"),
    path("real-estate/<int:pk>/loan/link/", views.property_loan_link, name="property_loan_link"),
    path("real-estate/<int:pk>/loan/<int:loan_pk>/unlink/", views.property_loan_unlink, name="property_loan_unlink"),
    path("real-estate/<int:pk>/ownership/add/", views.ownership_add, name="ownership_add"),
    path("ownership/<int:pk>/delete/", views.ownership_delete, name="ownership_delete"),
    path("real-estate/bulk/delete/", views.bulk_delete_realestate, name="realestate_bulk_delete"),
    path("real-estate/bulk/export/", views.bulk_export_realestate_csv, name="realestate_bulk_export_csv"),
    # Investments
    path("investments/", views.InvestmentListView.as_view(), name="investment_list"),
    path("investments/export/", views.export_investment_csv, name="investment_export_csv"),
    path("investments/create/", views.InvestmentCreateView.as_view(), name="investment_create"),
    path("investments/<int:pk>/", views.InvestmentDetailView.as_view(), name="investment_detail"),
    path("investments/<int:pk>/pdf/", views.export_pdf_investment_detail, name="investment_export_pdf"),
    path("investments/<int:pk>/edit/", views.InvestmentUpdateView.as_view(), name="investment_edit"),
    path("investments/<int:pk>/delete/", views.InvestmentDeleteView.as_view(), name="investment_delete"),
    path("investments/<int:pk>/loan/link/", views.investment_loan_link, name="investment_loan_link"),
    path("investments/<int:pk>/loan/<int:loan_pk>/unlink/", views.investment_loan_unlink, name="investment_loan_unlink"),
    path("investments/<int:pk>/participant/add/", views.participant_add, name="participant_add"),
    path("participant/<int:pk>/delete/", views.participant_delete, name="participant_delete"),
    path("investments/bulk/delete/", views.bulk_delete_investment, name="investment_bulk_delete"),
    path("investments/bulk/export/", views.bulk_export_investment_csv, name="investment_bulk_export_csv"),
    # Loans
    path("loans/", views.LoanListView.as_view(), name="loan_list"),
    path("loans/<int:pk>/inline-status/", views.inline_update_loan_status, name="loan_inline_status"),
    path("loans/export/", views.export_loan_csv, name="loan_export_csv"),
    path("loans/create/", views.LoanCreateView.as_view(), name="loan_create"),
    path("loans/<int:pk>/", views.LoanDetailView.as_view(), name="loan_detail"),
    path("loans/<int:pk>/pdf/", views.export_pdf_loan_detail, name="loan_export_pdf"),
    path("loans/<int:pk>/edit/", views.LoanUpdateView.as_view(), name="loan_edit"),
    path("loans/<int:pk>/delete/", views.LoanDeleteView.as_view(), name="loan_delete"),
    path("loans/<int:pk>/party/add/", views.loan_party_add, name="loan_party_add"),
    path("party/<int:pk>/delete/", views.loan_party_delete, name="loan_party_delete"),
    path("loans/bulk/delete/", views.bulk_delete_loan, name="loan_bulk_delete"),
    path("loans/bulk/export/", views.bulk_export_loan_csv, name="loan_bulk_export_csv"),
    # Insurance Policies
    path("policies/", views.InsurancePolicyListView.as_view(), name="policy_list"),
    path("policies/<int:pk>/inline-status/", views.inline_update_policy_status, name="policy_inline_status"),
    path("policies/export/", views.export_policy_csv, name="policy_export_csv"),
    path("policies/create/", views.InsurancePolicyCreateView.as_view(), name="policy_create"),
    path("policies/<int:pk>/", views.InsurancePolicyDetailView.as_view(), name="policy_detail"),
    path("policies/<int:pk>/pdf/", views.export_pdf_policy_detail, name="policy_export_pdf"),
    path("policies/<int:pk>/edit/", views.InsurancePolicyUpdateView.as_view(), name="policy_edit"),
    path("policies/<int:pk>/delete/", views.InsurancePolicyDeleteView.as_view(), name="policy_delete"),
    path("policies/<int:pk>/policyholder/add/", views.policyholder_add, name="policyholder_add"),
    path("policyholder/<int:pk>/delete/", views.policyholder_delete, name="policyholder_delete"),
    path("policies/bulk/delete/", views.bulk_delete_policy, name="policy_bulk_delete"),
    path("policies/bulk/export/", views.bulk_export_policy_csv, name="policy_bulk_export_csv"),
    # Vehicles
    path("vehicles/", views.VehicleListView.as_view(), name="vehicle_list"),
    path("vehicles/<int:pk>/inline-status/", views.inline_update_vehicle_status, name="vehicle_inline_status"),
    path("vehicles/export/", views.export_vehicle_csv, name="vehicle_export_csv"),
    path("vehicles/create/", views.VehicleCreateView.as_view(), name="vehicle_create"),
    path("vehicles/<int:pk>/", views.VehicleDetailView.as_view(), name="vehicle_detail"),
    path("vehicles/<int:pk>/pdf/", views.export_pdf_vehicle_detail, name="vehicle_export_pdf"),
    path("vehicles/<int:pk>/edit/", views.VehicleUpdateView.as_view(), name="vehicle_edit"),
    path("vehicles/<int:pk>/delete/", views.VehicleDeleteView.as_view(), name="vehicle_delete"),
    path("vehicles/<int:pk>/loan/link/", views.vehicle_loan_link, name="vehicle_loan_link"),
    path("vehicles/<int:pk>/loan/<int:loan_pk>/unlink/", views.vehicle_loan_unlink, name="vehicle_loan_unlink"),
    path("vehicles/<int:pk>/policy/link/", views.vehicle_policy_link, name="vehicle_policy_link"),
    path("vehicles/<int:pk>/policy/<int:policy_pk>/unlink/", views.vehicle_policy_unlink, name="vehicle_policy_unlink"),
    path("vehicles/<int:pk>/owner/add/", views.vehicle_owner_add, name="vehicle_owner_add"),
    path("vehicle-owner/<int:pk>/delete/", views.vehicle_owner_delete, name="vehicle_owner_delete"),
    path("vehicles/bulk/delete/", views.bulk_delete_vehicle, name="vehicle_bulk_delete"),
    path("vehicles/bulk/export/", views.bulk_export_vehicle_csv, name="vehicle_bulk_export_csv"),
    # Aircraft
    path("aircraft/", views.AircraftListView.as_view(), name="aircraft_list"),
    path("aircraft/<int:pk>/inline-status/", views.inline_update_aircraft_status, name="aircraft_inline_status"),
    path("aircraft/export/", views.export_aircraft_csv, name="aircraft_export_csv"),
    path("aircraft/create/", views.AircraftCreateView.as_view(), name="aircraft_create"),
    path("aircraft/<int:pk>/", views.AircraftDetailView.as_view(), name="aircraft_detail"),
    path("aircraft/<int:pk>/pdf/", views.export_pdf_aircraft_detail, name="aircraft_export_pdf"),
    path("aircraft/<int:pk>/edit/", views.AircraftUpdateView.as_view(), name="aircraft_edit"),
    path("aircraft/<int:pk>/delete/", views.AircraftDeleteView.as_view(), name="aircraft_delete"),
    path("aircraft/<int:pk>/loan/link/", views.aircraft_loan_link, name="aircraft_loan_link"),
    path("aircraft/<int:pk>/loan/<int:loan_pk>/unlink/", views.aircraft_loan_unlink, name="aircraft_loan_unlink"),
    path("aircraft/<int:pk>/policy/link/", views.aircraft_policy_link, name="aircraft_policy_link"),
    path("aircraft/<int:pk>/policy/<int:policy_pk>/unlink/", views.aircraft_policy_unlink, name="aircraft_policy_unlink"),
    path("aircraft/<int:pk>/owner/add/", views.aircraft_owner_add, name="aircraft_owner_add"),
    path("aircraft-owner/<int:pk>/delete/", views.aircraft_owner_delete, name="aircraft_owner_delete"),
    path("aircraft/bulk/delete/", views.bulk_delete_aircraft, name="aircraft_bulk_delete"),
    path("aircraft/bulk/export/", views.bulk_export_aircraft_csv, name="aircraft_bulk_export_csv"),
    # Inline notes editing for through models
    path("ownership/<int:pk>/notes/", views.ownership_notes, name="ownership_notes"),
    path("participant/<int:pk>/notes/", views.participant_notes, name="participant_notes"),
    path("party/<int:pk>/notes/", views.loan_party_notes, name="loan_party_notes"),
    path("vehicle-owner/<int:pk>/notes/", views.vehicle_owner_notes, name="vehicle_owner_notes"),
    path("aircraft-owner/<int:pk>/notes/", views.aircraft_owner_notes, name="aircraft_owner_notes"),
    path("policyholder/<int:pk>/notes/", views.policyholder_notes, name="policyholder_notes"),
]
