# Generated by Django 6.0.2 on 2026-02-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='response_notes',
            field=models.TextField(blank=True),
        ),
    ]
