# Generated by Django 6.0.2 on 2026-02-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='method',
            field=models.CharField(max_length=30),
        ),
    ]
