# Generated by Django 6.0.2 on 2026-02-10 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_followup_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='follow_up_days',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
