# Generated by Django 6.0.2 on 2026-02-10 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_followup_follow_up_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='reminder_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
