# Generated by Django 6.0.2 on 2026-02-10 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_followup_reminder_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='direction',
            field=models.CharField(choices=[('personal', 'Personal'), ('outbound', 'Outbound Request'), ('inbound', 'Inbound Request')], default='personal', max_length=10),
        ),
    ]
