# Generated by Django 6.0.2 on 2026-02-11 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_fk_rename_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('one_time', 'One-Time'), ('reference', 'Reference'), ('meeting', 'Meeting')], default='one_time', max_length=10),
        ),
    ]
