# Generated by Django 6.0.2 on 2026-02-11 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0002_alter_contactlog_stakeholder_and_more'),
        ('tasks', '0007_task_recurrence_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='stakeholder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='stakeholders.stakeholder'),
        ),
    ]
