# Generated by Django 6.0.2 on 2026-03-04 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_followup_stakeholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
