# Generated by Django 6.0.2 on 2026-03-20 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0005_stakeholder_firm_type'),
        ('tasks', '0009_add_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='stakeholders.stakeholder'),
        ),
    ]
