# Generated by Django 6.0.2 on 2026-03-25 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_task_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='meeting_url',
            field=models.URLField(blank=True, max_length=2000, verbose_name='Meeting link'),
        ),
    ]
