# Generated by Django 6.0.2 on 2026-03-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_add_meeting_url_and_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='meeting_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Meeting ID'),
        ),
        migrations.AddField(
            model_name='task',
            name='meeting_passcode',
            field=models.CharField(blank=True, max_length=50, verbose_name='Passcode'),
        ),
    ]
