# Generated by Django 6.0.2 on 2026-03-27 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_add_meeting_id_and_passcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reference_url',
            field=models.URLField(blank=True, max_length=2000, verbose_name='Reference link'),
        ),
    ]
