from django.urls import path
from . import views

app_name = "healthcare"

urlpatterns = [
    # Unified healthcare list
    path("", views.healthcare_list, name="healthcare_list"),
    # Tab settings
    path("tabs/", views.healthcare_tab_settings, name="healthcare_tab_settings"),
    path("tabs/add/", views.healthcare_tab_add, name="healthcare_tab_add"),
    path("tabs/<int:pk>/edit/", views.healthcare_tab_edit, name="healthcare_tab_edit"),
    path("tabs/<int:pk>/delete/", views.healthcare_tab_delete, name="healthcare_tab_delete"),
    # Providers
    path("providers/create/", views.ProviderCreateView.as_view(), name="provider_create"),
    path("providers/<int:pk>/", views.ProviderDetailView.as_view(), name="provider_detail"),
    path("providers/<int:pk>/pdf/", views.export_pdf_provider_detail, name="provider_export_pdf"),
    path("providers/<int:pk>/edit/", views.ProviderUpdateView.as_view(), name="provider_edit"),
    path("providers/<int:pk>/delete/", views.ProviderDeleteView.as_view(), name="provider_delete"),
    path("providers/<int:pk>/inline-status/", views.inline_update_provider_status, name="provider_inline_status"),
    path("providers/export/", views.export_provider_csv, name="provider_export_csv"),
    path("providers/bulk/delete/", views.bulk_delete_provider, name="bulk_delete_provider"),
    path("providers/<int:pk>/internal-notes/", views.provider_internal_notes, name="provider_internal_notes"),
    path("providers/<int:pk>/note/link/", views.provider_note_link, name="provider_note_link"),
    path("providers/<int:pk>/note/<int:note_pk>/unlink/", views.provider_note_unlink, name="provider_note_unlink"),
    path("providers/<int:pk>/legal/link/", views.provider_legal_link, name="provider_legal_link"),
    path("providers/<int:pk>/legal/<int:legal_pk>/unlink/", views.provider_legal_unlink, name="provider_legal_unlink"),
    # Conditions
    path("conditions/create/", views.ConditionCreateView.as_view(), name="condition_create"),
    path("conditions/<int:pk>/", views.ConditionDetailView.as_view(), name="condition_detail"),
    path("conditions/<int:pk>/edit/", views.ConditionUpdateView.as_view(), name="condition_edit"),
    path("conditions/<int:pk>/delete/", views.ConditionDeleteView.as_view(), name="condition_delete"),
    path("conditions/<int:pk>/inline-status/", views.inline_update_condition_status, name="condition_inline_status"),
    path("conditions/export/", views.export_condition_csv, name="condition_export_csv"),
    path("conditions/bulk/delete/", views.bulk_delete_condition, name="bulk_delete_condition"),
    path("conditions/<int:pk>/internal-notes/", views.condition_internal_notes, name="condition_internal_notes"),
    path("conditions/<int:pk>/note/link/", views.condition_note_link, name="condition_note_link"),
    path("conditions/<int:pk>/note/<int:note_pk>/unlink/", views.condition_note_unlink, name="condition_note_unlink"),
    path("conditions/<int:pk>/legal/link/", views.condition_legal_link, name="condition_legal_link"),
    path("conditions/<int:pk>/legal/<int:legal_pk>/unlink/", views.condition_legal_unlink, name="condition_legal_unlink"),
    # Prescriptions
    path("prescriptions/create/", views.PrescriptionCreateView.as_view(), name="prescription_create"),
    path("prescriptions/<int:pk>/", views.PrescriptionDetailView.as_view(), name="prescription_detail"),
    path("prescriptions/<int:pk>/pdf/", views.export_pdf_prescription_detail, name="prescription_export_pdf"),
    path("prescriptions/<int:pk>/edit/", views.PrescriptionUpdateView.as_view(), name="prescription_edit"),
    path("prescriptions/<int:pk>/delete/", views.PrescriptionDeleteView.as_view(), name="prescription_delete"),
    path("prescriptions/<int:pk>/inline-status/", views.inline_update_prescription_status, name="prescription_inline_status"),
    path("prescriptions/export/", views.export_prescription_csv, name="prescription_export_csv"),
    path("prescriptions/bulk/delete/", views.bulk_delete_prescription, name="bulk_delete_prescription"),
    path("prescriptions/<int:pk>/internal-notes/", views.prescription_internal_notes, name="prescription_internal_notes"),
    path("prescriptions/<int:pk>/note/link/", views.prescription_note_link, name="prescription_note_link"),
    path("prescriptions/<int:pk>/note/<int:note_pk>/unlink/", views.prescription_note_unlink, name="prescription_note_unlink"),
    path("prescriptions/<int:pk>/legal/link/", views.prescription_legal_link, name="prescription_legal_link"),
    path("prescriptions/<int:pk>/legal/<int:legal_pk>/unlink/", views.prescription_legal_unlink, name="prescription_legal_unlink"),
    # Supplements
    path("supplements/create/", views.SupplementCreateView.as_view(), name="supplement_create"),
    path("supplements/<int:pk>/", views.SupplementDetailView.as_view(), name="supplement_detail"),
    path("supplements/<int:pk>/edit/", views.SupplementUpdateView.as_view(), name="supplement_edit"),
    path("supplements/<int:pk>/delete/", views.SupplementDeleteView.as_view(), name="supplement_delete"),
    path("supplements/<int:pk>/inline-status/", views.inline_update_supplement_status, name="supplement_inline_status"),
    path("supplements/export/", views.export_supplement_csv, name="supplement_export_csv"),
    path("supplements/bulk/delete/", views.bulk_delete_supplement, name="bulk_delete_supplement"),
    path("supplements/<int:pk>/internal-notes/", views.supplement_internal_notes, name="supplement_internal_notes"),
    # Test Results
    path("test-results/create/", views.TestResultCreateView.as_view(), name="testresult_create"),
    path("test-results/<int:pk>/", views.TestResultDetailView.as_view(), name="testresult_detail"),
    path("test-results/<int:pk>/edit/", views.TestResultUpdateView.as_view(), name="testresult_edit"),
    path("test-results/<int:pk>/delete/", views.TestResultDeleteView.as_view(), name="testresult_delete"),
    path("test-results/<int:pk>/inline-status/", views.inline_update_testresult_status, name="testresult_inline_status"),
    path("test-results/export/", views.export_testresult_csv, name="testresult_export_csv"),
    path("test-results/bulk/delete/", views.bulk_delete_testresult, name="bulk_delete_testresult"),
    path("test-results/<int:pk>/internal-notes/", views.testresult_internal_notes, name="testresult_internal_notes"),
    # Visits
    path("visits/create/", views.VisitCreateView.as_view(), name="visit_create"),
    path("visits/<int:pk>/", views.VisitDetailView.as_view(), name="visit_detail"),
    path("visits/<int:pk>/edit/", views.VisitUpdateView.as_view(), name="visit_edit"),
    path("visits/<int:pk>/delete/", views.VisitDeleteView.as_view(), name="visit_delete"),
    path("visits/export/", views.export_visit_csv, name="visit_export_csv"),
    path("visits/bulk/delete/", views.bulk_delete_visit, name="bulk_delete_visit"),
    path("visits/<int:pk>/internal-notes/", views.visit_internal_notes, name="visit_internal_notes"),
    path("visits/<int:pk>/note/link/", views.visit_note_link, name="visit_note_link"),
    path("visits/<int:pk>/note/<int:note_pk>/unlink/", views.visit_note_unlink, name="visit_note_unlink"),
    # Advice
    path("advice/create/", views.AdviceCreateView.as_view(), name="advice_create"),
    path("advice/<int:pk>/", views.AdviceDetailView.as_view(), name="advice_detail"),
    path("advice/<int:pk>/edit/", views.AdviceUpdateView.as_view(), name="advice_edit"),
    path("advice/<int:pk>/delete/", views.AdviceDeleteView.as_view(), name="advice_delete"),
    path("advice/<int:pk>/inline-status/", views.inline_update_advice_status, name="advice_inline_status"),
    path("advice/export/", views.export_advice_csv, name="advice_export_csv"),
    path("advice/bulk/delete/", views.bulk_delete_advice, name="bulk_delete_advice"),
    path("advice/<int:pk>/internal-notes/", views.advice_internal_notes, name="advice_internal_notes"),
    # Appointments
    path("appointments/create/", views.AppointmentCreateView.as_view(), name="appointment_create"),
    path("appointments/<int:pk>/", views.AppointmentDetailView.as_view(), name="appointment_detail"),
    path("appointments/<int:pk>/pdf/", views.export_pdf_appointment_detail, name="appointment_export_pdf"),
    path("appointments/<int:pk>/edit/", views.AppointmentUpdateView.as_view(), name="appointment_edit"),
    path("appointments/<int:pk>/delete/", views.AppointmentDeleteView.as_view(), name="appointment_delete"),
    path("appointments/<int:pk>/inline-status/", views.inline_update_appointment_status, name="appointment_inline_status"),
    path("appointments/export/", views.export_appointment_csv, name="appointment_export_csv"),
    path("appointments/bulk/delete/", views.bulk_delete_appointment, name="bulk_delete_appointment"),
    path("appointments/<int:pk>/internal-notes/", views.appointment_internal_notes, name="appointment_internal_notes"),
    path("appointments/<int:pk>/note/link/", views.appointment_note_link, name="appointment_note_link"),
    path("appointments/<int:pk>/note/<int:note_pk>/unlink/", views.appointment_note_unlink, name="appointment_note_unlink"),
]
