# Generated by Django 6.0.2 on 2026-02-10 04:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('entity_type', models.CharField(db_index=True, default='contact', max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('trust_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('risk_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='stakeholders.stakeholder')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('from_stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='stakeholders.stakeholder')),
                ('to_stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='stakeholders.stakeholder')),
            ],
            options={
                'unique_together': {('from_stakeholder', 'to_stakeholder', 'relationship_type')},
            },
        ),
        migrations.CreateModel(
            name='ContactLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('method', models.CharField(max_length=30)),
                ('summary', models.TextField()),
                ('follow_up_needed', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_logs', to='stakeholders.stakeholder')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
