# Generated by Django 6.0.2 on 2026-02-11 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactlog',
            name='stakeholder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_logs', to='stakeholders.stakeholder'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='from_stakeholder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relationships_from', to='stakeholders.stakeholder'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='to_stakeholder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relationships_to', to='stakeholders.stakeholder'),
        ),
    ]
