# Generated by Django 6.0.2 on 2026-02-10 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0002_alter_contactlog_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholder',
            name='parent_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='stakeholders.stakeholder'),
        ),
    ]
