# Generated by Django 6.0.2 on 2026-03-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0003_stakeholdertab'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholder',
            name='website',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
