# Generated by Django 6.0.2 on 2026-03-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0004_stakeholder_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholder',
            name='firm_type',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
    ]
