# Generated by Django 6.0.2 on 2026-03-12 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0013_allow_multiple_roles_per_stakeholder'),
        ('legal', '0011_add_case_log'),
        ('stakeholders', '0005_stakeholder_firm_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('from_name', models.CharField(blank=True, max_length=255)),
                ('from_email', models.EmailField(blank=True, max_length=255)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('provider', models.CharField(default='gmail', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_aircraft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_links', to='assets.aircraft')),
                ('related_investment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_links', to='assets.investment')),
                ('related_lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_links', to='assets.lease')),
                ('related_legal_matter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_links', to='legal.legalmatter')),
                ('related_loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_links', to='assets.loan')),
                ('related_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_links', to='assets.insurancepolicy')),
                ('related_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_links', to='assets.realestate')),
                ('related_stakeholder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_links', to='stakeholders.stakeholder')),
                ('related_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_links', to='assets.vehicle')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
