# Generated by Django 6.0.2 on 2026-03-28 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_links', '0002_emaillink_message_count'),
        ('tasks', '0014_add_tasklink_remove_reference_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillink',
            name='related_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_links', to='tasks.task'),
        ),
    ]
