# Generated by Django 6.0.2 on 2026-03-31 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_links', '0003_emaillink_related_task'),
        ('notes', '0012_add_scratchpad'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillink',
            name='related_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_links', to='notes.note'),
        ),
    ]
