# Generated by Django 6.0.2 on 2026-03-19 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, default='', max_length=255)),
                ('model', models.CharField(default='claude-sonnet-4-6-20250514', max_length=100)),
                ('max_tokens', models.PositiveIntegerField(default=4096)),
                ('temperature', models.DecimalField(decimal_places=2, default=1.0, help_text='0.0 = deterministic, 1.0 = default, 2.0 = maximum creativity', max_digits=3)),
            ],
            options={
                'verbose_name': 'Assistant Settings',
                'verbose_name_plural': 'Assistant Settings',
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Chat', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField(blank=True)),
                ('tool_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
