# Generated by Django 6.0.2 on 2026-03-20 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantsettings',
            name='model',
            field=models.CharField(default='claude-sonnet-4-6', max_length=100),
        ),
    ]
