# Generated by Django 6.0.2 on 2026-03-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_alter_assistantsettings_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantsettings',
            name='max_tokens',
            field=models.PositiveIntegerField(default=8192),
        ),
        migrations.AlterField(
            model_name='assistantsettings',
            name='temperature',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='0.0 = deterministic, 1.0 = default, 2.0 = maximum creativity', max_digits=3),
        ),
    ]
