# Generated by Django 6.0.2 on 2026-03-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_alter_assistantsettings_max_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantsettings',
            name='owner_name',
            field=models.CharField(blank=True, default='', help_text='Your name, so the assistant knows not to create a stakeholder for you.', max_length=100),
        ),
    ]
