# Generated by Django 6.0.2 on 2026-03-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0004_assistantsettings_owner_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-is_pinned', 'sort_order', '-updated_at']},
        ),
        migrations.AddField(
            model_name='chatsession',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
