# Generated by Django 6.0.2 on 2026-03-25 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0005_add_session_pin_and_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantsettings',
            name='default_reminder_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Default reminder (minutes before due time) when creating tasks. 0 = no auto-reminder.'),
        ),
    ]
