# Generated by Django 6.0.2 on 2026-06-12 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0006_add_default_reminder_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='running', max_length=10)),
                ('client_disconnected', models.BooleanField(default=False)),
                ('confirm_required', models.BooleanField(default=False)),
                ('request_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('final_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assistant.chatmessage')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='assistant.chatsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
