# Generated by Django 6.0.2 on 2026-07-04 22:23

from django.db import migrations, models


def abandon_running_turns(apps, schema_editor):
    """Finalize any pre-existing running turns before the unique constraint
    lands. Duplicate running rows for one session would make AddConstraint
    fail outright; and any turn still marked running at migration time is
    dead anyway — deploys restart the container, killing stream workers
    mid-turn (exactly what state=abandoned means).
    """
    AssistantTurn = apps.get_model("assistant", "AssistantTurn")
    AssistantTurn.objects.filter(state="running").update(state="abandoned")


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0007_assistantturn'),
    ]

    operations = [
        migrations.RunPython(abandon_running_turns, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='assistantturn',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'running')), fields=('session',), name='one_running_turn_per_session'),
        ),
    ]
