# Generated by Django 6.0.2 on 2026-07-11 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0008_assistantturn_one_running_turn_per_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantsettings',
            name='max_tokens',
            field=models.PositiveIntegerField(default=12288),
        ),
        migrations.AlterField(
            model_name='assistantsettings',
            name='model',
            field=models.CharField(default='claude-sonnet-5', max_length=100),
        ),
    ]
