# Generated by Django 6.0.2 on 2026-04-24 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='is_reference',
            field=models.BooleanField(default=False),
        ),
    ]
